StrainArchive/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^management/', include('management.urls', namespace = "management")),
    url(r'^user/', include('userprofile.urls', namespace = "userprofile")),
    url(r'^search/', include('search.urls', namespace = "search")),
    url(r'^cart/', include('cart.urls', namespace = "cart")),
    url(r'^', include('archive.urls', namespace = "archive"))
]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^addToBasket/(?P<strain_pk>\d+)/$', views.add_to_basket, name = 'add_to_basket'),
    url(r'^removeFromBasket/(?P<strain_pk>\d+)/$', views.remove_from_basket, name = 'remove_from_basket'),
    url(r'^checkout/', views.checkout, name = "checkout"),
    url(r'^clearBasket/', views.clear_basket, name = "clearBasket"),
    url(r'checkPromotion/(?P<promotion_code>[\w\-]+)/$', views.check_promotion, name = "check_promotion"),
    url(r'cancelPromotion/(?P<promotion_code>[\w\-]+)/$', views.cancel_promotion, name = "cancel_promotion"),
    url(r'^success/', views.success, name = "success"),
]

management/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.management_dashboard, name = "dashboard"),
    url(r'^strains', views.management_strains, name = "strains"),
    url(r'^sales', views.management_sales, name = "sales"),
    url(r'^users', views.management_users, name = "users"),
    url(r'^getQuoteDetails/(?P<quote_pk>\d+)/$', views.get_quote_details, name = "get_quote_details"),
    url(r'^getOrderDetails/(?P<order_pk>\d+)/$', views.get_order_details, name = "get_order_details"),
    url(r'^getPromoCodes/(?P<promo_pk>\d+)/$', views.get_promo_codes, name = "get_promo_codes"),
    url(r'^sendQuote/(?P<quote_pk>\d+)/$', views.send_quote, name = "send_quote"),
    url(r'^updateUserStatus/(?P<user_pk>\d+)/$', views.update_user_status, name = "update_user_status"),
    url(r'^login/', views.login, name = "login"),
    url(r'^logoutUser/', views.logout_user, name = "logout_user"),
]

management/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class ManagementUserProfile(models.Model):

    first_name = models.CharField(max_length = 20)
    last_name = models.CharField(max_length = 20)
    user = models.OneToOneField(User)

    def get_full_name(self):
        
        return "%s %s" % (self.first_name, self.last_name)

management/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.core import serializers
from archive.models import Strain
from django.contrib.auth.models import User
from cart.models import Quote, Order, ConfirmedBasket, Purchase, Promotion, PromotionCode
from forms import CreateNewPromotionForm, GenerateNewCodesForm, EditOrderForm, LoginForm, NewUserForm
from django.http import HttpResponse
import json
from datetime import datetime
from django.shortcuts import redirect

from django.contrib.auth import logout





def logout_user(request):

    logout(request)

    return redirect("management:login")




def update_user_status(request, user_pk):

    try:

        user = User.objects.get(pk = user_pk)
    
    except User.DoesNotExist:

        data = {"status": "ERROR", "message": "User not found"}
    
    else:

        if user.is_active:

            user.is_active = False

        else:

            user.is_active = True
        
        user.save()
        
        data = {"status": "OK"}

    return HttpResponse(
        json.dumps(data),
        content_type = "application/json"
    )


def send_quote(request, quote_pk):

    try:

        quote = Quote.objects.get(pk = quote_pk)
    
    except Quote.DoesNotExist:

        pass
    
    else:

        newOrder = Order.objects.create(
            quote = quote
        )

        quote.status = "S"
        quote.save()

        messages.success(request, "The quote has been sent to %s successfully." % quote.customer_email)

        return HttpResponse(
            json.dumps({"status": "OK"}),
            content_type = "application/json"
        )
        


# view to get and return promotional codes for promotion with pk == promotion_pk
def get_promo_codes(request, promo_pk):

    # try to find promotion
    try:

        promo = Promotion.objects.get(pk = promo_pk)
    
    except Promotion.DoesNotExist:

        pass
    
    else:

        # generate list of dicts with data for each code
        codes = [
            {
                "pk": code.pk,
                "code": code.code,
                "number_of_uses": code.number_of_uses,
                "max_usages": code.max_usages,
                "active": code.active
            } for code in promo.promotioncode_set.all()
        ]
    
    # send data back to page
    return HttpResponse(
        json.dumps(codes),
        content_type = "application/json"
    )




# view to get order details
def get_order_details(request, order_pk):

    # check order exists
    try:
    
        order = Order.objects.get(pk = order_pk)
    
    except Order.DoesNotExist:
        
        # process case if order not existing
        messages.error(request, "Details for quote could not be located")
        order = None
    
    else:

        order_data = {
            "customer_name": order.quote.customer_name,
            "customer_email": order.quote.customer_email,
            "status": order.get_verbose_status_name(),
            "status_code": order.status,
            "payment_method": order.get_verbose_payment_method_name(),
            "payment_method_code": order.payment_method,
            "start_date": order.start_date.strftime('%d/%m/%Y'),
            "delivery_address": order.quote.delivery_address,
        }

        if order.cirms_number:
            order_data["cirms_number"] = order.cirms_number
        
        if order.finance_reference_number:
            order_data["finance_reference_number"] = order.finance_reference_number
        
        if order.payment_order:
            
            payment_order = order.payment_order

            if payment_order.pdf:
                order_data["payment_order_pdf"] = payment_order.get_pdf_filename()
            
            if payment_order.reference_number:
                order_data["payment_order_reference_number"] = payment_order.reference_number

        if order.shop_order:
            shop_order = order.shop_order
        
            if shop_order.order_number:
                order_data["shop_order_number"] = shop_order.order_number
            
            if shop_order.transaction_number:
                order_data["shop_transaction_number"] = shop_order.transaction_number

            
        if order.invoice_file:
            order_data["invoice_file"] = order.get_invoice_filename()

        if order.post_date:
            order_data["post_date"] = order.post_date.strftime('%d/%m/%Y')
        else:
            order_data["post_date"] = "N/A"

        if order.received_date:
            order_data["received_date"] = order.received_date.strftime('%d/%m/%Y')
        else:
            order_data["received_date"] = "N/A"

        
        

    return HttpResponse(
        json.dumps(order_data),
        content_type = "application/json"
    )

# view to get quote details
def get_quote_details(request, quote_pk):

    # check quote exists
    try:
    
        quote = Quote.objects.get(pk = quote_pk)
    
    except Quote.DoesNotExist:
        
        # process case if quote not existing
        messages.error(request, "Details for quote could not be located")
        quote = None
    
    else:

        # create dict representing quote
        quote_data = {
            "customer_name": quote.customer_name,
            "customer_email": quote.customer_email,
            "funding_type": quote.get_verbose_funding_type_name(),
            "billing_address": quote.billing_address,
            "delivery_address": quote.delivery_address,
            "customer_notes": quote.customer_note,
        }

        # if bbsrc code present, add to dict
        if quote.bbsrc_code:
            quote_data["bbsrc_code"] = quote.bbsrc_code
        else:
            quote_data["bbsrc_code"] = ""
        
        # check existence of basket and add to dict
        if quote.basket:
            quote_data["basket"] = quote.basket.as_dict()
        else:
            quote_data["basket"] = ""

    return HttpResponse(
        json.dumps(quote_data),
        content_type = "application/json"
    )




# management dashboard view
def management_dashboard(request):


    return render(
        request,
        "management/dashboard.html",
        {

        }
    )

# strain management view
def management_strains(request):

    return render(
        request,
        "management/strains.html",
        {
            "strains": Strain.objects.all()
        }
    )




# sales management view
def management_sales(request):

    createNewPromotionForm = CreateNewPromotionForm()
    generateCodesForm = GenerateNewCodesForm()
    editOrderForm = EditOrderForm()

    if request.method == "POST":

        if "editOrderForm" in request.POST:

            print "P:", request.POST
            print "F:", request.FILES

            editOrderForm = EditOrderForm(request.POST, request.FILES)

            if editOrderForm.is_valid():

                editOrderForm.process(request)
            
            else:

                editOrderForm.process_errors(request)


    if request.method == "POST":

        if "generateCodesForm" in request.POST:

            generateCodesForm = GenerateNewCodesForm(request.POST)

            if generateCodesForm.is_valid():

                generateCodesForm.process(request)
            
            else:

                generateCodesForm.process_errors(request)

        if "createNewPromotionForm" in request.POST:

            createNewPromotionForm = CreateNewPromotionForm(request.POST)

            if createNewPromotionForm.is_valid():

                createNewPromotionForm.process(request)
            
            else:

                createNewPromotionForm.process_errors(request)
    

    return render(
        request,
        "management/sales.html",
        {
            "editOrderForm": editOrderForm,
            "generateCodesForm": generateCodesForm,
            "createNewPromotionForm": createNewPromotionForm,
            "quotes": Quote.objects.all(),
            "promotions": Promotion.objects.all()
        }
    )



# user management view
def management_users(request):

    if request.method == "POST":

        new_user_form = NewUserForm(request.POST)

        if new_user_form.is_valid():

            new_user_form.process(request)
        
        else:

            new_user_form.process_errors(request)
    
    else:

        new_user_form = NewUserForm()

    return render(
        request,
        "management/users.html",
        {
            "users": User.objects.all(),
            "new_user_form": new_user_form
        }
    )


# view for management login
def login(request):

    if request.method == "POST":

        login_form = LoginForm(request.POST)

        if login_form.is_valid():

            if login_form.process(request):

                return redirect("management:dashboard")

        else:

            login_form.process_errors(request)

    else:

        login_form = LoginForm()

    return render(
        request,
        "management/login.html",
        {
            "login_form": login_form
        }
    )

management/templates/management/dashboard.html
{% extends "management/managementBase.html" %}
{% load staticfiles %}

{% block extra_css_files %}
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
{% endblock %}
{% block extra_js_files %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.9.1/d3.min.js"></script>
{% endblock %}


{% block inpage_js %}
    <script>
        
        $(document).ready(function() {
            $(".displayContainer").width($(".headerContainer").width() - 90);
        });

    </script>
{% endblock %}

{% block header_text %}
    <h2 class="headerText">Management: Dashboard</h2>
{% endblock %}

{% block dash_element %}
    <img src="{% static 'images/dashIcon_selected.png' %}" class="menuToggleIcon" id="selectedDashIcon">
{% endblock %}


{% block content %}
    <div class="col-md-12"><br></div>
    <div class="col-md-12 graphRow">
        <div class="col-md-6 leftSection">
            <div class="col-md-12">
                <h2>Graph A</h2>
            </div>
            <div class="col-md-12 graphContainer" id="numberOfStrainsGraphContainer">
            </div>
        </div>
        <div class="col-md-6 rightSection">
            <div class="col-md-12">
                <h2>Graph B</h2>
            </div>
            <div class="col-md-12 graphContainer" id="dailyDownloadsGraphContainer">
            </div>
        </div>
    </div>
    <div class="col-md-12"><br></div>
    <div class="col-md-12 graphRow">
        <div class="col-md-6 leftSection">
            <div class="col-md-12">
                <h2>Graph C</h2>
            </div>
            <div class="col-md-12 graphContainer" id="numberOfStrainsGraphContainer">
            </div>
        </div>
        <div class="col-md-6 rightSection">
            <div class="col-md-12">
                <h2>Graph D</h2>
            </div>
            <div class="col-md-12 graphContainer" id="dailyDownloadsGraphContainer">
            </div>
        </div>
    </div>
{% endblock %}

management/templates/management/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block extra_css_files %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
{% endblock %}
{% block extra_js_files %}
    <script src="{% static 'js/login.js' %}"></script>
{% endblock %}

{% block header_text %}
    <h2>Admin Login</h2>
{% endblock %}

{% block page_content %}

    <form action="." id="login_form" name="login_form" method="post">
        {% csrf_token %}
        {% for field in login_form %}
            {{field.as_hidden}}
        {% endfor %}
    </form>

    <div class="col-md-12 loginContainer">
        <div class="col-md-12" align="middle">
            <h2>Login To Your Account</h2>
            <br>
        </div>
        <div class="col-md-12">
            <div class="col-md-6">
                <h4>Username:</h4>
            </div>
            <div class="col-md-6">
                <input type="text" class="form-control" id="usernameInput">
            </div>
        </div>
        <div class="col-md-12">
            <div class="col-md-6">
                <h4>Password:</h4>
            </div>
            <div class="col-md-6">
                <input type="password" class="form-control" id="passwordInput">
            </div>
        </div>
        <div class="col-md-12">
            <br>
            <input type="submit" class="btn btn-success" value="LOGIN" form="login_form" id="submitLoginForm">
        </div>
    </div>
    
{% endblock %}

management/templates/management/managementBase.html
{% extends "base.html" %}
    {% load staticfiles %}
        
        <div class="col-md-12 container mainContainer">

            {% block page_content %}

                <div class="container menuContainerCollapsed">

                    <div class="collapsedMenuElement" align="middle">
                        <img src="{% static 'images/menuIcon.png' %}" class="menuToggleIcon" id="menuToggle">
                    </div>

                    <div class="collapsedMenuElement" align="middle">
                        {% block dash_element %}
                            <a href="{% url 'management:dashboard' %}">
                                <img src="{% static 'images/dashIcon.png' %}" class="menuToggleIcon" id="dashIcon">
                            </a>
                        {% endblock %}
                    </div>

                    <div class="collapsedMenuElement" align="middle">
                        {% block strain_element %}
                            <a href="{% url 'management:strains' %}">
                                <img src="{% static 'images/strainIcon.png' %}" class="menuToggleIcon" id="strainIcon">
                            </a>
                        {% endblock %}
                    </div>

                    <div class="collapsedMenuElement" align="middle">
                        {% block sales_element %}
                        <a href="{% url 'management:sales' %}">
                            <img src="{% static 'images/salesIcon.png' %}" class="menuToggleIcon" id="salesIcon">
                        </a>
                        {% endblock %}
                    </div>

                    <div class="collapsedMenuElement" align="middle">
                        {% block users_element %}
                            <a href="{% url 'management:users' %}">
                                <img src="{% static 'images/usersIcon.png' %}" class="menuToggleIcon" id="usersIcon">
                            </a>
                        {% endblock %}
                    </div>
                    
                </div>

                <div class="container displayContainer">
                    {% block content %}
                    {% endblock %}
                </div>

                <div class="col-md-12 pageFooter" align="right">
                    <a href="{% url 'management:logout_user' %}">
                        <img src="{% static 'images/logoutIcon.png' %}" class="logoutIcon" id="logout">
                    </a>
                </div>

            {% endblock %}

        </div>

    </body>

</html>

management/templates/management/sales.html
{% extends "management/managementBase.html" %}
{% load staticfiles %}

{% block extra_css_files %}
    <link href="{% static 'css/sales.css' %}" rel="stylesheet">
    <link href="{% static 'css/promoModal.css' %}" rel="stylesheet">
{% endblock %}

{% block extra_js_files %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.9.1/d3.min.js"></script>
    <script type="text/javascript" src="{% static 'js/confirmation.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/quotes.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/promotions.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/orders.js' %}"></script>
{% endblock %}


{% block inpage_js %}
    <script>
        
        $(document).ready(function() {
            $(".displayContainer").width($(".headerContainer").width() - 90);
        });

    </script>
{% endblock %}

{% block header_text %}
    <h2 class="headerText">Management: Sales</h2>
{% endblock %}

{% block sales_element %}
    <img src="{% static 'images/salesIcon_selected.png' %}" class="menuToggleIcon" id="selectedSalesIcon">
{% endblock %}


{% block content %}

    {% include 'include/costModal.html' %}
    {% include 'include/quoteDetailsModal.html' %}
    {% include 'include/orderDetailsModal.html' %}
    {% include 'include/editOrderModal.html' %}
    {% include 'include/newPromoModal.html' %}
    {% include 'include/viewCodesModal.html' %}
    {% include 'include/generateCodesModal.html' %}
    {% include 'include/confirmationModal.html' %}

    <form id="createNewPromotionForm" method="post" name="createNewPromotionForm">
        {% csrf_token %}
        {% for field in createNewPromotionForm %}
            {{field.as_hidden}}
        {% endfor %}
    </form>
    <form id="generateCodesForm" method="post" name="generateCodesForm">
        {% csrf_token %}
        {% for field in generateCodesForm %}
            {{field.as_hidden}}
        {% endfor %}
    </form>
    <form id="editOrderForm" method="post" name="editOrderForm" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in editOrderForm %}
            {{field.as_hidden}}
        {% endfor %}
    </form>
    
    <div class="col-md-12"><br></div>

    <div class="col-md-12" id="mainViewContainer">
        <div class="col-md-12">
            <h2>Quotes and Orders</h2>
        </div>
        <div class="col-md-12" id="quotesTableContainer">
            <table class="table table-hover" id="quotesTable">
                <thead>
                    <tr>
                        <th class="dateCell">Submission Date</th>
                        <th class="customerCell">Customer</th>
                        <th class="costCell">Cost</th>
                        <th class="quoteStatusCell">Quote Status</th>
                        <th class="orderStatusCell">Order Status</th>
                        <th class="viewCell"></th>
                        <th class="sendQuoteCell"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for q in quotes %}
                        <tr class="quoteRow" id="{{q.pk}}">
                            <td class="dateCell">{{q.creation_date}}
                            <td class="customerCell">{{q.customer_name}}</td>
                            {% if q.basket.applied_promotion %}
                                <td class="costCell"><b>£{{q.basket.promotion_cost}}</b></td>
                            {% else %}
                                <td class="costCell"><b>£{{q.basket.total_cost}}</b></td>
                            {% endif %}
                            <td class="quoteStatusCell">
                                {{q.get_verbose_status_name}}
                            </td>
                            {% if q.order %}
                                <td class="orderStatusCell">{{q.order.get_verbose_status_name}}</td>
                            {% else %}
                                <td class="orderStatusCell"><p>No Order Present</p></td>
                            {% endif %}
                            <td class="viewCell" align="middle">
                                <button type="button" class="btn btn-xs btn-primary viewQuote">View Quote</button>
                                {% if q.order %}
                                    <button type="button" class="btn btn-xs btn-primary viewOrder" id="order_{{q.order.pk}}">View Order</button>
                                {% else %}
                                    <button type="button" class="btn btn-xs btn-primary viewOrder" disabled>View Order</button>
                                {% endif %}
                            </td>
                            {% if q.status == "S" %}
                                <td class="sendQuoteCell">
                                    <button type="button" class="btn btn-xs btn-danger sendQuote" disabled>Quote Sent!</button>
                                </td>
                            {% else %}
                                <td class="sendQuoteCell">
                                    <button type="button" class="btn btn-xs btn-danger sendQuote">Send Quote</button>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h2>Promotions</h2>
        </div>
        <div class="col-md-6">
            <h2>Placeholder...</h2>
        </div>
        <div class="col-md-6" id="promoContainer">
            <table class="table table-hover" id="promotionsTable">
                <thead>
                    <tr>
                        <th class="promoNameCell">Name</th>
                        <th class="promoDescriptionCell">Description</th>
                        <th class="promoStartDateCell">Start Date</th>
                        <th class="promoExpiryDateCell">Expiry Date</th>
                        <th class="promoExpiredCell">Expired</th>
                        <th class="promoCodesCell">Codes</th>
                    </tr>
                </thead>
                <tbody>
                    {% for promo in promotions %}
                        <tr class="promoRow" id="promo_{{promo.pk}}">
                            <td class="promoNameCell">{{promo.name}}</td>
                            <td class="promoDescriptionCell">{{promo.description}}</td>
                            <td class="promoStartDateCell">{{promo.start_date}}</td>
                            <td class="promoExpiryDateCell">{{promo.expiry_date}}</td>
                            <td class="promoExpiredCell">{{promo.expired}}</td>
                            <td class="promoCodesCell">
                                <p><button type="button" class="btn btn-xs btn-primary viewCodes">View</button></p>
                                <p><button type="button" class="btn btn-xs btn-primary generateCodes">Generate</button></p>
                            </td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="6" align="middle"><button type="button" class="btn btn-success" id="openNewPromoModal">Create New</button></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6" id="placeholderContainer">
        </div>
    </div>

{% endblock %}

management/templates/management/strains.html
{% extends "management/managementBase.html" %}
{% load staticfiles %}

{% block extra_css_files %}
    <link href="{% static 'css/strains.css' %}" rel="stylesheet">
{% endblock %}
{% block extra_js_files %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.9.1/d3.min.js"></script>
{% endblock %}


{% block inpage_js %}
    <script>
        
        $(document).ready(function() {
            $(".displayContainer").width($(".headerContainer").width() - 90);
        });

    </script>
{% endblock %}

{% block header_text %}
    <h2 class="headerText">Management: Strains</h2>
{% endblock %}

{% block strain_element %}
    <img src="{% static 'images/strainIcon_selected.png' %}" class="menuToggleIcon" id="selectedStrainIcon">
{% endblock %}

{% block content %}
    <div class="col-md-12"><br></div>
    
    <div class="col-md-12" id="strainTableContainer">

        <table class="table table-hover" id="strainTable">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Date Added</th>
                    <th>Sales</th>
                </tr>
            </thead>
            <tbody>
                {% for strain in strains %}
                    <tr class="strainRow" id="{{strain.pk}}">
                        <td class="nameCell">{{strain.name}}</td>
                        <td class="dateAddedCell">{{strain.date_added}}</td>
                        <td class="salesCell">{{strain.purchases.all.count}}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
    </div>

{% endblock %}

management/templates/management/users.html
{% extends "management/managementBase.html" %}
{% load staticfiles %}

{% block extra_css_files %}
    <link href="{% static 'css/users.css' %}" rel="stylesheet">
{% endblock %}
{% block extra_js_files %}
    <script src="{% static 'js/newUser.js' %}"></script>
    <script src="{% static 'js/editUser.js' %}"></script>
{% endblock %}


{% block inpage_js %}
    <script>
        
        $(document).ready(function() {
            $(".displayContainer").width($(".headerContainer").width() - 90);
        });

    </script>
{% endblock %}

{% block header_text %}
    <h2 class="headerText">Management: Users</h2>
{% endblock %}

{% block users_element %}
    <img src="{% static 'images/usersIcon_selected.png' %}" class="menuToggleIcon" id="selectedUsersIcon">
{% endblock %}


{% block content %}
    
    {% include 'include/newUserModal.html' %}

    <form id="newUserForm" method="post" name="newUserForm">
        {% csrf_token %}
        {% for field in new_user_form %}
            {{field.as_hidden}}
        {% endfor %}
    </form>

    <div class="col-md-12"><br></div>

    <div class="col-md-12" id="usersContainer">
        <div class="col-md-12">
            <h2>Users</h2>
        </div>
        <div class="col-md-12" id="usersTableContainer">

            <table class="table table-hover" id="usersTable">
                <thead>
                    <tr>
                        <th>Username</th>
                        <th>Name</th>
                        <th>Active</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr class="userRow" id="{{user.pk}}">
                        <td>{{user.username}}</td>
                        <td>{{user.managementuserprofile.get_full_name}}</td>
                        <td>
                            <div class="dropdown">
                                {% if user.is_active %}
                                    <button class="btn btn-xs btn-primary dropdown-toggle activationDropdown" id="activeDropdown" type="button" data-toggle="dropdown">
                                        Active
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu activationMenu">
                                        <li class="promoTypeOption">Deactivate</li>
                                    </ul>
                                {% else %}
                                    <button class="btn btn-xs btn-primary dropdown-toggle activationDropdown" type="button" data-toggle="dropdown">
                                        Not Active
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu activationMenu">
                                        <li class="promoTypeOption">Activate</li>
                                    </ul>
                                {% endif %}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="3" align="middle">
                            <button type="button" class="btn btn-success" id="openNewUserModal">+</button>
                        </td>
                    </tr>
                </tbody>
            </table>
            
        </div>
    </div>
{% endblock %}