StrainArchive/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^management/', include('management.urls', namespace = "management")),
    url(r'^user/', include('userprofile.urls', namespace = "userprofile")),
    url(r'^search/', include('search.urls', namespace = "search")),
    url(r'^cart/', include('cart.urls', namespace = "cart")),
    url(r'^', include('archive.urls', namespace = "archive"))
]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^addToBasket/(?P<strain_pk>\d+)/$', views.add_to_basket, name = 'add_to_basket'),
    url(r'^removeFromBasket/(?P<strain_pk>\d+)/$', views.remove_from_basket, name = 'remove_from_basket'),
    url(r'^checkout/', views.checkout, name = "checkout"),
    url(r'^clearBasket/', views.clear_basket, name = "clearBasket"),
    url(r'checkPromotion/(?P<promotion_code>[\w\-]+)/$', views.check_promotion, name = "check_promotion"),
    url(r'cancelPromotion/(?P<promotion_code>[\w\-]+)/$', views.cancel_promotion, name = "cancel_promotion"),
    url(r'^success/', views.success, name = "success"),
]

cart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from archive.models import Strain
from datetime import datetime
import json
import os

class Promotion(models.Model):

    PROMOTION_TYPES = (
        ("FPR", "Fixed Price Reduction"),
        ("PPR", "Percentage Reduction"),
        ("NS", "Not Set")
    )

    name = models.CharField(max_length = 50)
    description = models.TextField(null = True)

    start_date = models.DateField(default = datetime.now)
    expiry_date = models.DateField(null = True)

    expired = models.BooleanField(default = False)
    promotion_parameters = models.TextField(null = True)
    promotion_type = models.CharField(max_length = 4, choices = PROMOTION_TYPES, default = "NS")

    def get_verbose_promotion_type_name(self):

        return self.get_promotion_type_display()

    def check_expiry_date(self):

        if datetime.now().date() >= self.expiry_date.date():

            return True
        
        else:

            return False
    
    def update_expiry_date(self):

        if self.check_expiry_date():

            self.expired = True
        
        else:

            self.expired = False
        
        self.save()


class PromotionCode(models.Model):

    code = models.CharField(max_length = 10, unique = True)
    max_usages = models.IntegerField(default = 1)
    number_of_uses = models.IntegerField(default = 0)
    active = models.BooleanField(default = True)
    promotion = models.ForeignKey(Promotion, null = True)

    def check_usage_limit_hit(self):

        if self.number_of_uses >= self.max_usages:

            return True

        else:

            return False






# how many of which strain to be purchased
class Purchase(models.Model):

    # which strain, how many, and total cost for purchase
    strain = models.ForeignKey(Strain)
    quantity = models.IntegerField(default = 0)
    cost = models.FloatField(default = 0.0)

# collection of purchases and user which requested them
class ConfirmedBasket(models.Model):

    # purchases in order and summed cost for all of them
    purchases = models.ManyToManyField(Purchase)
    total_cost = models.FloatField(default = 0.0)
    promotion_cost = models.FloatField(null = True)
    applied_promotion = models.ForeignKey(Promotion, null = True)
    applied_code = models.ForeignKey(PromotionCode, null = True)


    # put data for basket into dict
    def as_dict(self):

        output = {"purchases": [], "total_cost": self.total_cost}

        if self.promotion_cost:
            output["promotion_data"] = {
                "applied_code": self.applied_code.code,
                "promotion_cost": self.promotion_cost,
                "promotion_pk": self.applied_promotion.pk,
                "promotion_description": self.applied_promotion.description,
                "promotion_name": self.applied_promotion.name
            }
        
        else:

            output["promotion_data"] = "NONE"

        for purchase in self.purchases.all():
            output["purchases"].append(
                {
                    "strain_id": purchase.strain.pk,
                    "strain_name": purchase.strain.name,
                    "quantity": purchase.quantity,
                    "cost": purchase.cost
                }
            )
        
        return output

    # serialize basket into json string
    def as_json_string(self):

        return json.dumps(self.as_dict())


# quote for cost of basket
class Quote(models.Model):

    # status of quote
    STATUS_CHOICES = (
        ("P", "Pending"),
        ("S", "Sent"),
        ("A", "Accepted"),
        ("R", "Rejected"),
        ("C", "Cancelled")
    )

    # available types of funding
    FUNDING_TYPES = (
        ("NC", "Non-Commercial"),
        ("B", "BBSRC"),
        ("I", "Industry"),
        ("UB", "Internal UoB"),
        ("NS", "Not Set")
    )
    
    status = models.CharField(default = "P", choices = STATUS_CHOICES, max_length = 1)
    funding_type = models.CharField(max_length = 2, choices = FUNDING_TYPES, default = "NS")

    # bbsrc funding code (required if bbsrc funding put on quote)
    bbsrc_code = models.CharField(max_length = 10, null = True)
    
    # customer details
    # (note can be attached to quote by customer)
    customer_name = models.CharField(max_length = 100, null = True)
    customer_email = models.EmailField(null = True)
    customer_note = models.TextField(default = "")

    # basket for which quote relates to
    basket = models.OneToOneField(ConfirmedBasket, null = True)
    
    # addresses
    billing_address = models.TextField(default = "")
    delivery_address = models.TextField(default = "")
    
    # date at which quote was created
    creation_date = models.DateTimeField(default = datetime.now)

    # get display names for funding type and status
    def get_verbose_funding_type_name(self):

        return self.get_funding_type_display()

    def get_verbose_status_name(self):

        return self.get_status_display()


class PaymentOrder(models.Model):
    
    # numbers stored as char fields so large ints dont need to be stored
    reference_number = models.CharField(max_length = 30, null = True)
    pdf = models.FileField(null = True)

    def get_pdf_filename(self):
        return os.path.basename(self.pdf.name)


class ShopOrder(models.Model):

    # numbers stored as char fields so large ints dont need to be stored
    order_number = models.CharField(max_length = 30, null = True)
    transaction_number = models.CharField(max_length = 30, null = True)


# represents dispatched product/order status
class Order(models.Model):

    # status of order
    STATUS_CHOICES = (
        ("PP", "Pending Payment"),
        ("P", "Processing"),
        ("AD", "Awaiting Dispatch"),
        ("D", "Dispatched"),
        ("R", "Received"),
        ("V", "Void")
    )

    PAYMENT_METHODS = (
        ("PO", "Payment Order"),
        ("OS", "Online Shop"),
        ("NS", "Not Set")
    )

    status = models.CharField(
        default = "PP",
        choices = STATUS_CHOICES,
        max_length = 2
    )

    payment_method = models.CharField(
        default = "NS",
        choices = PAYMENT_METHODS,
        max_length = 2
    )

    # quote for which order is for
    quote = models.OneToOneField(Quote, null = True)

    # dates for each stage of order
    start_date = models.DateTimeField(default = datetime.now)
    post_date = models.DateTimeField(null = True)
    received_date = models.DateTimeField(null = True)

    cirms_number = models.CharField(max_length = 30, null = True)
    
    finance_reference_number = models.CharField(max_length = 30, null = True)
    payment_order = models.OneToOneField(PaymentOrder, null = True)
    shop_order = models.OneToOneField(ShopOrder, null = True)

    invoice_file = models.FileField(null = True)

    def get_invoice_filename(self):
        return os.path.basename(self.invoice_file.name)

    # get the display name for the payment type
    def get_verbose_payment_method_name(self):

        return self.get_payment_method_display()

    # get display name for order status
    def get_verbose_status_name(self):

        return self.get_status_display()

cart/forms.py
from django import forms
from django.contrib import messages
from archive.models import Strain
from . models import Quote
import json
import cart.basket_utils

class QuoteForm(forms.Form):

    # verbose name mappings for funding types
    FUNDING_TYPES = (
        ("NC", "Non-Commercial"),
        ("B", "BBSRC"),
        ("I", "Industry"),
        ("UB", "Internal UoB")
    )

    # form fields
    customer_name = forms.CharField(max_length = 100, required = True)
    email = forms.EmailField(required = True)
    billing_address = forms.CharField(required = True, max_length = 200)
    delivery_address = forms.CharField(required = True, max_length = 200)
    funding_type = forms.CharField(required = True, max_length = 2)
    bbsrc_code = forms.CharField(required = False, max_length = 10)
    note = forms.CharField(required = False, max_length = 250)

    # clean the data and process the form
    def process(self, request):

        # get cleaned data
        cleaned_name = self.cleaned_data["customer_name"]
        cleaned_email = self.cleaned_data["email"]
        cleaned_billing_address = self.cleaned_data["billing_address"]
        cleaned_delivery_address = self.cleaned_data["delivery_address"]
        cleaned_funding_type = self.cleaned_data["funding_type"]
        cleaned_bbsrc_code = self.cleaned_data["bbsrc_code"]
        cleaned_note = self.cleaned_data["note"]

        # if needed, make sure that a BBSRC code has been given
        if cleaned_funding_type == "B":
            
            if not cleaned_bbsrc_code:
                
                messages.error(request, "BBSRC Code is needed for BBSRC funded purchases.")

            else:

                # create BBSRC funded quote
                newQuote = Quote.objects.create(
                    customer_name = cleaned_name,
                    customer_email = cleaned_email,
                    funding_type = cleaned_funding_type,
                    bbsrc_code = cleaned_bbsrc_code,
                    billing_address = cleaned_billing_address,
                    delivery_address = cleaned_delivery_address
                )
        
        else:

            # create non-BBSRC funded quote
            newQuote = Quote.objects.create(
                customer_name = cleaned_name,
                customer_email = cleaned_email,
                funding_type = cleaned_funding_type,
                billing_address = cleaned_billing_address,
                delivery_address = cleaned_delivery_address
            )

        # add the note if one was submitted
        if cleaned_note:
            newQuote.customer_note = cleaned_note

        # save the session basket to the database
        confirmed_basket = cart.basket_utils.save_session_basket_to_db(request)

        # add the basket to the quote and save
        newQuote.basket = confirmed_basket
        newQuote.save()

        # clear the session basket
        request.session["basket"] = cart.basket_utils.generate_empty_basket()
        request.session.modified = True
        

    def process_errors(self, request):
        
        error_dict = json.loads(self.errors.as_json())
        for key in error_dict:
            for error in error_dict[key]:
                messages.error(request, "Error: %s - %s" % (key, error["message"]))

cart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse
from archive.models import Strain
from . forms import QuoteForm
from . import basket_utils
from . import promo_utils
from . models import Promotion, PromotionCode
import json
from datetime import datetime

# view for checkout completion
def success(request):

    return render(request, "cart/checkoutSuccess.html", {})


# generates an empty basket (dict) and sets session basket to new empty basket
def clear_basket(request):

    # generate empty basket and set session basket
    request.session["basket"] = basket_utils.generate_empty_basket()
    request.session.modified = True

    # return empty basket to page
    return HttpResponse(
        json.dumps(request.session["basket"]),
        content_type = "application/json"
    )


def cancel_promotion(request, promotion_code):

    try:

        promotion_code = PromotionCode.objects.get(code = promotion_code)

    except PromotionCode.DoesNotExist:

        # code does not exist
        data = {"status": "NOT_FOUND"}

    else:

        promotion_code.number_of_uses -= 1
        promotion_code.save()
        request.session["basket"]["promotion"] = {
            "promotion_code": "",
            "promotion_pk": "",
            "promotion_total_cost": 0.0
        }

        request.session.modified = True

        data = {"status": "SUCCESS", "basket": request.session["basket"]}


    return HttpResponse(
        json.dumps(data),
        content_type = "application/json"
    )


    # return basket and status to the page
    return HttpResponse(
        json.dumps(data),
        content_type = "application/json"
    )


# applies promotion code to basket
# returns promotion status and basket
def check_promotion(request, promotion_code):

    # attempt to find promotion code in database
    try:

        promotion_code = PromotionCode.objects.get(code = promotion_code)

    except PromotionCode.DoesNotExist:

        # code does not exist
        data = {"status": "NOT_FOUND"}

    else:

        if promotion_code.promotion.expired:

            # promotion has expired
            data = {"status": "EXPIRED"}

        elif promotion_code.promotion.start_date > datetime.now().date():

            # promotion is not yet running
            data = {"status": "NOT_YET_RUNNING"}
        
        elif promotion_code.check_usage_limit_hit():

            # code has reached usage limit
            data = {"status": "USEAGE_LIMIT"}
        
        elif not promotion_code.active:

            # code is not active
            data = {"status": "INACTIVE"}

        else:

            # if code is valid and active, apply to basket
            promo_utils.apply_code_to_session_basket(request, promotion_code)
            
            promotion_code.save()

            # calculate remaining usages
            remaining_usages = promotion_code.max_usages - promotion_code.number_of_uses

            # code has been applied successfully
            data = {
                "status": "SUCCESS",
                "basket": request.session["basket"],
                "promo_name": promotion_code.promotion.name,
                "promo_description": promotion_code.promotion.description,
                "remaining_usages": remaining_usages
            }

        # return basket and status to the page
        return HttpResponse(
            json.dumps(data),
            content_type = "application/json"
        )


# adds strain to session basket
def add_to_basket(request, strain_pk):
    
    # try and find strain in database
    try:

        selected_strain = Strain.objects.get(pk = strain_pk)

    except Strain.DoesNotExist:

        pass

    else:

        # add strain to session basket
        basket_utils.add_to_basket(request, selected_strain)

        # recalculate cost and update session basket
        basket_utils.set_basket_cost(request)


    # return basket to the page
    return HttpResponse(
        json.dumps(request.session["basket"]),
        content_type = "application/json"
    )


# remove strain from session basket
def remove_from_basket(request, strain_pk):

    # try to find strain in database
    try:

        selected_strain = Strain.objects.get(pk = strain_pk)
    
    except Strain.DoesNotExist:

        pass

    else:

        # remove strain from session basket
        basket_utils.remove_from_basket(request, selected_strain)

        # recalculate cost and update session basket
        basket_utils.set_basket_cost(request)

    # return basket to page
    return HttpResponse(
        json.dumps(request.session["basket"]),
        content_type = "application/json"
    )


# render the checkout page and handle quote requests
def checkout(request):

    if request.method == "POST":

        quote_form = QuoteForm(request.POST)

        if quote_form.is_valid():

            quote_form.process(request)

            return redirect("cart:success")
            
        
        else:

            quote_form.process_errors(request)
    
    else:

        quote_form = QuoteForm()

    return render(
        request,
        "cart/checkout.html",
        {
            "quote_form": quote_form,
            "basket": request.session["basket"]
        }
    )

cart/templates/include/basket.html
<div class="col-md-12 row-eq-height" id="basketHeaderRow">
    <div class="col-md-10">
        <h2>My Basket</h2>
    </div>
    <div class="col-md-2" id="editButtonContainer">
        <button type="button" class="btn btn-xs btn-primary" id="basketEditButton">EDIT</button>
    </div>
</div>
<div class="col-md-12" id="basketContentTableContainer">
    <table class="table table-hover" id="basketContentTable">
        <thead>
            <tr>
                <th class="removeItemCell"></th>
                <th class="itemNameCell basketHeaderCell">Name</th>
                <th class="itemAmountCell basketHeaderCell">Amount</th>
                <th class="itemCostCell basketHeaderCell">Cost</th>
            </tr>
        </thead>
        <tbody>
            {% for item in basket.items %}
                <tr class="itemRow" id="{{item.pk}}">
                    <td class="removeItemCell"><button type="button" class="btn btn-xs btn-danger removeFromBasket">&times;</button></td>
                    <td class="itemNameCell">{{item.name}}</td>
                    <td class="itemAmountCell">{{item.amount}}</td>
                    <td class="itemCostCell">{{item.cost}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="col-md-12 row-eq-height" id="totalContainer">
    <div class="col-md-4">
        <h3>Total:</h3>
    </div>
    <div class="col-md-8" align="right">
        <h3 id="basketTotalCost">£{{basket.total_cost}}</h3>
    </div>
</div>
<div class="col-md-12" class="basketFooter" id="basketFooter_clear" hidden>
    <button type="button" class="btn btn-danger" id="clearBasket">Clear Basket</button>
</div>
<div class="col-md-12" class="basketFooter" id="basketFooter_checkout">
    <a href="{% url 'cart:checkout' %}">
        <input type="submit" class="btn btn-success" id="checkout" form="" value="Checkout">
    </a>
</div>

cart/templates/include/billingAddressTab.html
<div id="billingAddressTab" class="tab-pane fade">,
    <div class="col-md-12"><br></div>
    <div class="col-md-12">
        <div class="col-md-6">
            <h4><b>Billing</b> Address:</h4>
        </div>
        <div class="col-md-6">
            <textarea class="form-control addressInput" rows="10" cols="20" id="billingAddressInput"></textarea>
        </div>
    </div>
    <div class="col-md-12"><br></div>
    <div class="col-md-12">
        <div class="col-md-6" align="left">
            <button type="button" class="btn btn-success previousButton" id="frame_2">Previous</button>
        </div>
        <div class="col-md-6" align="right">
            <button type="button" class="btn btn-success nextButton" id="billingNext">Next</button>
        </div>
    </div>
</div>

cart/templates/include/checkoutSummaryModal.html
<!-- Modal -->
<div id="checkoutSummaryModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Checkout Summary</h4>
            </div>

            <div class="modal-body col-md-12">
                <div class="col-md-12">
                    <div class="col-md-12">
                        <h3>Your Orders</h3>
                    </div>
                    <div class="col-md-12">
                        {% for item in basket.items %}
                            <div class="col-md-12">
                                <div class="col-md-2">
                                    {{item.amount}}x
                                </div>
                                <div class="col-md-8">
                                    {{item.name}}
                                </div>
                                <div class="col-md-2" align="right">
                                    £{{item.cost}}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-md-12" align="right">
                            <div class="col-md-2"></div>
                            <div class="col-md-8" align="right"><h4>TOTAL:</h4></div>
                            <div class="col-md-2"><h4>£{{basket.total_cost}}</h4></div>
                        </div>
                    </div>
                    <div class="col-md-12"><hr></div>
                    <div class="col-md-12">
                        <h3>Your Details</h3>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <h4>Name:</h4>
                        </div>
                        <div class="col-md-6">
                            <h4 class="summaryField" id="nameFieldSummary">Some Name</h4>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <h4>Email:</h4>
                        </div>
                        <div class="col-md-6">
                            <h4 class="summaryField" id="emailFieldSummary">Some Email</h4>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <h4>Funding Type:</h4>
                        </div>
                        <div class="col-md-6">
                            <h4 class="summaryField" id="fundingFieldSummary">Some funding</h4>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="col-md-6">
                            <h4>BBSRC Code:</h4>
                        </div>
                        <div class="col-md-6">
                            <h4 class="summaryField" id="bbsrcCodeSummary">N/A</h4>
                        </div>
                    </div>
                    <div class="col-md-12"><hr></div>
                    <div class="col-md-12">
                        <h3>Billing Address</h3>
                    </div>
                    <div class="col-md-12">
                        <textarea readonly class="form-control addressInput" rows="10" id="billingAddressSummary"></textarea>
                    </div>
                    <div class="col-md-12"><hr></div>
                    <div class="col-md-12">
                        <h3>Delivery Address</h3>
                    </div>
                    <div class="col-md-12">
                        <textarea readonly class="form-control addressInput" rows="10" id="deliveryAddressSummary"></textarea>
                    </div>
                    <div class="col-md-12">
                        <h3>Notes:</h3>
                    </div>
                    <div class="col-md-12">
                        <h4 id="noteSummary"></h4>
                    </div>
                </div>
            </div>
            
            <div class="col-md-12"><hr></div>

            <div class="col-md-12">
                <div class="col-md-6" align="left">
                    <button type="button" class="btn btn-basic" data-dismiss="modal">Close</button>
                </div>
                <div class="col-md-6" align="right">
                    <button type="button" class="btn btn-success" id="confirmQuoteForm">Confirm</button>
                </div>
            </div>
            <div class="modal-footer">
            </div>
        </div>

    </div>
</div>

cart/templates/include/deliveryAddressTab.html
<div id="deliveryAddressTab" class="tab-pane fade">
    <div class="col-md-12"><br></div>
    <div class="col-md-12">
        <div class="col-md-6">
            <h4><b>Delivery</b> Address:</h4>
        </div>
        <div class="col-md-6">
            <textarea class="form-control addressInput" rows="10" cols="20" id="deliveryAddressInput"></textarea>
        </div>
    </div>
    <div class="col-md-12"><br></div>
    <div class="col-md-12">
        <div class="col-md-6" align="left">
            <button type="button" class="btn btn-success previousButton" id="frame_1">Previous</button>
        </div>
        <div class="col-md-6" align="right">
            <button type="button" class="btn btn-success nextButton" id="deliveryNext">Next</button>
        </div>
    </div>
</div>

cart/templates/include/errorModal.html
<!-- Modal -->
<div id="errorModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" id="errorModalHeader">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Warning</h4>
            </div>

            <div class="modal-body col-md-12">
                <div class="col-md-12">
                    <h3 id="errorMessage"></h3>
                </div>
            </div>
            
            <div class="col-md-12"><hr></div>

            <div class="col-md-12" align="right">
                <button type="button" class="btn btn-success" data-dismiss="modal">OK</button>
            </div>
            <div class="modal-footer">
            </div>
        </div>

    </div>
</div>

cart/templates/include/notesTab.html
<div id="notesTab" class="tab-pane fade">
    <div class="col-md-12"><br></div>
    <div class="col-md-12">
        <div class="col-md-6" id="promoDetailsContainer">
            <h4>Additional Notes:</h4>
        </div>
        <div class="col-md-6" id="basketOverview">
            <textarea class="form-control" rows="10" cols="20" id="noteInput"></textarea>
        </div>
    </div>
    <div class="col-md-12">
        <div class="col-md-6" align="left">
            <button type="button" class="btn btn-success previousButton" id="frame_4">Previous</button>
        </div>
        <div class="col-md-6" align="right">
            <button type="button" class="btn btn-success" id="viewSummary">Submit</button>
        </div>
    </div>
</div>

cart/templates/include/paymentTab.html
<div id="paymentDetailsTab" class="tab-pane fade in active">
    <div class="col-md-12"><br></div>
    <div class="col-md-12">
        <div class="col-md-5">
            <h4>Name:</h4>
        </div>
        <div class="col-md-7">
            <input type="text" class="form-control" id="nameInput">
        </div>
    </div>
    <div class="col-md-12"><br></div>
    <div class="col-md-12">
        <div class="col-md-5">
            <h4>Email:</h4>
        </div>
        <div class="col-md-7">
            <input type="text" class="form-control" id="emailInput">
        </div>
    </div>
    <div class="col-md-12"><br></div>
    <div class="col-md-12">
        <div class="col-md-5">
            <h4>Confirm Email:</h4>
        </div>
        <div class="col-md-7">
            <input type="text" class="form-control" id="confirmEmailInput">
        </div>
    </div>
    <div class="col-md-12"><br></div>
    <div class="col-md-12">
        <div class="col-md-5">
            <h4>Funding Type:</h4>
        </div>
        <div class="col-md-7">
            <div class="dropdown">
                
                <button class="btn btn-primary dropdown-toggle" id="fundingTypeDropdown" type="button" data-toggle="dropdown">
                    Select Funding Type
                    <span class="caret"></span>
                </button>
                
                <ul class="dropdown-menu" id="fundingTypeDropdownMenu">
                    <li class="fundingTypeOption" id="NC">Non-Commercial</li>
                    <li class="fundingTypeOption" id="B">BBSRC</li>
                    <li class="fundingTypeOption" id="I">Industry</li>
                    <li class="fundingTypeOption" id="UB">Internal UoB</li>
                    <li class="fundingTypeOption" id="NS">Not Set</li>
                </ul>

            </div>
        </div>
    </div>
    <div class="col-md-12"><br></div>
    <div class="col-md-12" id="bbsrcContainer">
        <div class="col-md-5">
            <h4>BBSRC Code:</h4>
        </div>
        <div class="col-md-7">
            <input type="text" class="form-control" id="bbsrcCodeInput">
        </div>
    </div>
    <div class="col-md-12"><br></div>
    <div class="col-md-12">
        <div class="col-md-6" align="left">
            <button type="button" class="btn btn-success previousButton" id="frame_0" disabled>Previous</button>
        </div>
        <div class="col-md-6" align="right">
            <button type="button" class="btn btn-success nextButton" id="paymentNext">Next</button>
        </div>
    </div>
</div>

cart/templates/include/promoDetailsModal.html
<!-- Modal -->
<div id="promoDetailsModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header" id="promoDetailsModalHeader">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="promotionDetailsTitle">APPLY PROMOTIONAL CODE</h4>
            </div>

            <div class="modal-body col-md-12">
                <div class="col-md-12">
                    <div class="col-md-6">
                        <h4>Promotion:</h4>
                    </div>
                    <div class="col-md-6">
                        <h4 id="promoName"></h4>
                    </div>
                </div>
                <div class="col-md-12"><hr></div>
                <div class="col-md-12" align="middle">
                    <h4 id="promoDescription"></h4>
                </div>
                <div class="col-md-12"><hr></div>
                <div class="col-md-12" align="middle">
                    <h4 id="promoApplicationSummary"></h4>
                </div>
            </div>
            
            <div class="col-md-12"><hr></div>

            <div class="col-md-12">
                <div class="col-md-6" align="left">
                    <button type="button" class="btn btn-default" data-dismiss="modal" id="cancelPromotionApplication">Cancel</button>
                </div>
                <div class="col-md-6" align="right">
                    <button type="button" class="btn btn-success" data-dismiss="modal" id="confirmCode">Confirm</button>
                </div>
            </div>
            <div class="modal-footer">
            </div>
        </div>

    </div>
</div>