StrainArchive/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^management/', include('management.urls', namespace = "management")),
    url(r'^user/', include('userprofile.urls', namespace = "userprofile")),
    url(r'^search/', include('search.urls', namespace = "search")),
    url(r'^cart/', include('cart.urls', namespace = "cart")),
    url(r'^', include('archive.urls', namespace = "archive"))
]

archive/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.homepage, name = "home"),
]

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^addToBasket/(?P<strain_pk>\d+)/$', views.add_to_basket, name = 'add_to_basket'),
    url(r'^removeFromBasket/(?P<strain_pk>\d+)/$', views.remove_from_basket, name = 'remove_from_basket'),
    url(r'^checkout/', views.checkout, name = "checkout"),
    url(r'^clearBasket/', views.clear_basket, name = "clearBasket"),
    url(r'checkPromotion/(?P<promotion_code>[\w\-]+)/$', views.check_promotion, name = "check_promotion"),
    url(r'cancelPromotion/(?P<promotion_code>[\w\-]+)/$', views.cancel_promotion, name = "cancel_promotion"),
    url(r'^success/', views.success, name = "success"),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="{% static 'css/global.css' %}" rel="stylesheet">
        <script src="{% static 'js/messages.js' %}"></script>
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
        <link href="{% static 'css/messages.css' %}" rel="stylesheet">

        {% block extra_css_files %}
        {% endblock %}

        {% block extra_js_files %}
        {% endblock %}

        {% block inpage_js %}
        {% endblock %}

    </head>

    <body>

        {% include 'include/messages.html' %}

        <div class="col-md-12 container headerContainer">
            <div class="col-md-6" align="left">
                <a href="{% url 'archive:home' %}">
                    <h2 class="headerText">MicrobesNG Strain Archive</h2>
                </a>
            </div>
            <div class="col-md-6" align="right">
                {% block header_text %}
                {% endblock %}
            </div>
        </div>

        <div class="col-md-12 container mainContainer">

            {% block page_content %}


            {% endblock %}

        </div>

    </body>

</html>